apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          command: ["redis-server", "--appendonly", "yes"]
          securityContext:
            runAsUser: 0
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
